import { useState } from "react";
import {
  AreaChart, Area, BarChart, Bar, LineChart, Line,
  XAxis, YAxis, Tooltip, ResponsiveContainer, Cell,
  PieChart, Pie, Legend
} from "recharts";

const C = {
  bg:"#F8FAFC",white:"#FFFFFF",dark:"#0F172A",
  gray100:"#F1F5F9",gray200:"#E2E8F0",gray400:"#94A3B8",gray600:"#475569",gray700:"#334155",
  indigo:"#6366F1",indigoLight:"#EEF2FF",
  green:"#10B981",greenLight:"#ECFDF5",
  red:"#EF4444",redLight:"#FEF2F2",
  amber:"#F59E0B",amberLight:"#FFFBEB",
  orange:"#F97316",
  blue:"#0EA5E9",
  purple:"#8B5CF6",
};
const F = { d:"Syne, sans-serif", b:"DM Sans, sans-serif" };

// DATA
const sentimentData=[{day:"1",positive:18,neutral:42,negative:40},{day:"5",positive:22,neutral:38,negative:40},{day:"10",positive:20,neutral:40,negative:40},{day:"15",positive:28,neutral:38,negative:34},{day:"20",positive:32,neutral:36,negative:32},{day:"25",positive:35,neutral:35,negative:30},{day:"30",positive:38,neutral:36,negative:26}];
const hourlyData=[{h:"6am",comments:12,spam:3},{h:"7am",comments:28,spam:8},{h:"8am",comments:65,spam:22},{h:"9am",comments:120,spam:45},{h:"10am",comments:98,spam:31},{h:"11am",comments:145,spam:52},{h:"12pm",comments:189,spam:78},{h:"1pm",comments:210,spam:88},{h:"2pm",comments:176,spam:64},{h:"3pm",comments:134,spam:41},{h:"4pm",comments:98,spam:28},{h:"5pm",comments:72,spam:18}];
const responseRateData=[{intent:"Crisis",auto:45,manual:52},{intent:"Complaint",auto:38,manual:29},{intent:"Purchase",auto:72,manual:18},{intent:"Question",auto:61,manual:24},{intent:"Compliment",auto:55,manual:12}];
const intentData=[{label:"General Queries",count:962,color:C.indigo,pct:13},{label:"Rude Comments",count:1223,color:C.red,pct:16.5},{label:"Scam/Spam",count:1072,color:C.orange,pct:14.5},{label:"Appreciation",count:527,color:C.green,pct:7.1},{label:"Pricing Issues",count:424,color:C.amber,pct:5.7},{label:"Network Issues",count:370,color:C.purple,pct:5},{label:"Others",count:2232,color:C.gray400,pct:30.1}];
const topPosts=[{title:"Epic Plan 30GB Launch",sentiment:78,spam:8,platform:"FB",comments:1240},{title:"SIM Now Pay Later",sentiment:65,spam:12,platform:"IG",comments:890},{title:"11.11 Sale Campaign",sentiment:52,spam:28,platform:"TT",comments:2100},{title:"Independence Day Post",sentiment:85,spam:4,platform:"FB",comments:560},{title:"Laal Network vs Onic",sentiment:41,spam:35,platform:"IG",comments:1780}];
const complaintThemes=[{theme:"Pricing Inconsistency",count:424,delta:23},{theme:"Network Quality",count:370,delta:68},{theme:"Onboarding Issues",count:105,delta:22},{theme:"App Performance",count:25,delta:-12},{theme:"Customer Support",count:100,delta:99}];
const platformData=[{platform:"Facebook",comments:3840,sentiment:38,responseRate:72,spam:14.2},{platform:"Instagram",comments:2190,sentiment:44,responseRate:68,spam:11.8},{platform:"TikTok",comments:1377,sentiment:29,responseRate:54,spam:19.4}];
const triggerData=[{name:"Spam Keywords",fires:1072,action:"Auto-hide",overrides:12,precision:98.9},{name:"Purchase Intent",fires:424,action:"Auto-reply",overrides:4,precision:99.1},{name:"Escalation Words",fires:187,action:"Escalate",overrides:8,precision:95.7},{name:"Appreciation",fires:527,action:"Auto-like",overrides:2,precision:99.6},{name:"Pricing Query",fires:312,action:"Auto-reply",overrides:18,precision:94.2},{name:"Crisis Keywords",fires:89,action:"Escalate",overrides:5,precision:94.4}];
const inboxItems=[{id:1,platform:"FB",user:"Abdul Qudoos Khan",comment:"یہ اونک کیسا نیٹ ورک ہے",intent:"Complaint",sentiment:"Negative",time:"2m ago",status:"pending"},{id:2,platform:"IG",user:"Ali Raza",comment:"Sir Kia onic per all network available ha",intent:"Question",sentiment:"Neutral",time:"5m ago",status:"pending"},{id:3,platform:"TT",user:"Salman Yousafzai",comment:"بہت بہت شکریہ اونک مجھے سم مل گیا",intent:"Compliment",sentiment:"Positive",time:"8m ago",status:"replied"},{id:4,platform:"FB",user:"Qudrat Ullah",comment:"i have smart card how can i get the sim",intent:"Purchase",sentiment:"Positive",time:"15m ago",status:"pending"},{id:5,platform:"IG",user:"Muhammad Jamil",comment:"I am new joiner, how do I activate?",intent:"Question",sentiment:"Neutral",time:"22m ago",status:"escalated"},{id:6,platform:"FB",user:"Aman Khan",comment:"Network issues in Hyderabad area, please resolve",intent:"Complaint",sentiment:"Negative",time:"31m ago",status:"pending"},{id:7,platform:"TT",user:"Hafeez Rahman",comment:"اٹک میں دستیاب ہے",intent:"Question",sentiment:"Neutral",time:"45m ago",status:"replied"},{id:8,platform:"FB",user:"Mubashira Shams",comment:"Is ma Kia special ha",intent:"Question",sentiment:"Neutral",time:"1h ago",status:"pending"}];
const engagementTrend=[{week:"W1",responseRate:58,reengagement:36},{week:"W2",responseRate:61,reengagement:38},{week:"W3",responseRate:64,reengagement:40},{week:"W4",responseRate:64,reengagement:43}];
const heatmapData=(()=>{const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];const hours=["6am","8am","10am","12pm","2pm","4pm","6pm","8pm","10pm"];return days.map(d=>({day:d,hours:hours.map(h=>({h,v:Math.floor(Math.random()*100)}))}));})();

// SHARED COMPONENTS
function PBadge({p}){const col={FB:"#1877F2",IG:"#E1306C",TT:"#000"};return<span style={{background:col[p]||"#666",color:"#fff",fontSize:10,fontWeight:700,padding:"2px 7px",borderRadius:4,flexShrink:0}}>{p}</span>;}
function SPill({platform,status}){const c={green:{bg:"#DCFCE7",text:"#16A34A",dot:"#22C55E"},amber:{bg:"#FEF9C3",text:"#CA8A04",dot:"#EAB308"},red:{bg:"#FEE2E2",text:"#DC2626",dot:"#EF4444"}}[status];return<div style={{display:"flex",alignItems:"center",gap:7,background:c.bg,borderRadius:8,padding:"7px 12px"}}><div style={{width:7,height:7,borderRadius:"50%",background:c.dot}}/><span style={{fontFamily:F.b,fontSize:12,fontWeight:600,color:c.text}}>{platform}</span></div>;}
function SLabel({children,color=C.indigo}){return<div style={{display:"flex",alignItems:"center",gap:8,marginBottom:14}}><div style={{width:3,height:16,background:color,borderRadius:2}}/><span style={{fontFamily:F.d,fontSize:12,fontWeight:700,color:C.dark,letterSpacing:"0.07em",textTransform:"uppercase"}}>{children}</span></div>;}
function Card({children,style={}}){return<div style={{background:C.white,borderRadius:14,padding:"20px 22px",border:`1px solid ${C.gray100}`,boxShadow:"0 1px 4px rgba(0,0,0,0.04)",...style}}>{children}</div>;}
function KTile({label,value,delta,deltaLabel,dark,onClick,active}){return<div onClick={onClick} style={{background:dark?"linear-gradient(135deg,#0F172A,#1E293B)":C.white,borderRadius:12,padding:"18px",flex:1,minWidth:0,border:active?`2px solid ${C.indigo}`:`1px solid ${C.gray100}`,boxShadow:active?`0 0 0 3px ${C.indigoLight}`:"0 1px 4px rgba(0,0,0,0.04)",cursor:onClick?"pointer":"default"}}><div style={{fontFamily:F.b,fontSize:10,fontWeight:600,color:C.gray400,letterSpacing:"0.08em",textTransform:"uppercase",marginBottom:7}}>{label}</div><div style={{fontFamily:F.d,fontSize:26,fontWeight:800,color:dark?C.white:C.dark,lineHeight:1}}>{value}</div>{delta!==undefined&&<div style={{marginTop:5,fontFamily:F.b,fontSize:11,color:delta>0?C.red:C.green}}>{delta>0?"▲":"▼"} {Math.abs(delta)}% {deltaLabel}</div>}{deltaLabel&&delta===undefined&&<div style={{marginTop:5,fontFamily:F.b,fontSize:11,color:dark?C.green:C.gray400}}>{deltaLabel}</div>}</div>;}
function IBadge({intent}){const m={Crisis:{bg:"#FEE2E2",t:"#DC2626"},Complaint:{bg:"#FEF3C7",t:"#D97706"},Spam:{bg:"#FFF7ED",t:"#EA580C"},Question:{bg:"#EEF2FF",t:"#4F46E5"},Compliment:{bg:"#ECFDF5",t:"#059669"},Purchase:{bg:"#F0FDF4",t:"#16A34A"}};const s=m[intent]||{bg:C.gray100,t:C.gray600};return<span style={{background:s.bg,color:s.t,fontSize:10,fontWeight:700,padding:"2px 8px",borderRadius:20,whiteSpace:"nowrap"}}>{intent}</span>;}
function SBadge({status}){const m={pending:{bg:"#FEF9C3",t:"#CA8A04",l:"Pending"},replied:{bg:"#DCFCE7",t:"#16A34A",l:"Replied"},escalated:{bg:"#FEE2E2",t:"#DC2626",l:"Escalated"}};const s=m[status]||{bg:C.gray100,t:C.gray600,l:status};return<span style={{background:s.bg,color:s.t,fontSize:10,fontWeight:700,padding:"2px 8px",borderRadius:20,whiteSpace:"nowrap"}}>{s.l}</span>;}

// DRILL DOWN MODAL
function DrillDown({metric,onClose}){
  if(!metric)return null;
  const content={
    "Comments Today":{title:"Comments Today — By Platform",body:<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:16}}>{platformData.map(p=><div key={p.platform} style={{background:C.gray100,borderRadius:10,padding:"14px 16px"}}><div style={{fontSize:11,color:C.gray400,fontWeight:600,marginBottom:4}}>{p.platform}</div><div style={{fontFamily:F.d,fontSize:24,fontWeight:800,color:C.dark}}>{p.comments.toLocaleString()}</div></div>)}</div><ResponsiveContainer width="100%" height={160}><BarChart data={platformData}><XAxis dataKey="platform" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="comments" fill={C.indigo} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></>},
    "Auto-Processed":{title:"Automation Coverage",body:<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:16}}>{[["Auto-hide","3,811",C.red],["Auto-reply","1,240",C.green],["Auto-like","527",C.amber]].map(([l,v,c])=><div key={l} style={{background:C.gray100,borderRadius:10,padding:"14px 16px"}}><div style={{fontSize:11,color:C.gray400,fontWeight:600,marginBottom:4}}>{l}</div><div style={{fontFamily:F.d,fontSize:24,fontWeight:800,color:c}}>{v}</div></div>)}</div><ResponsiveContainer width="100%" height={140}><BarChart data={[{n:"Auto-hide",v:3811},{n:"Auto-reply",v:1240},{n:"Auto-like",v:527}]}><XAxis dataKey="n" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="v" fill={C.indigo} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></>},
    "Response Rate":{title:"Response Rate by Intent",body:<ResponsiveContainer width="100%" height={220}><BarChart data={responseRateData}><XAxis dataKey="intent" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false} unit="%"/><Tooltip/><Bar dataKey="auto" name="Auto" fill={C.indigo} radius={[4,4,0,0]}/><Bar dataKey="manual" name="Manual" fill="#C7D2FE" radius={[4,4,0,0]}/><Legend/></BarChart></ResponsiveContainer>},
    "Comments Hidden":{title:"Hidden Comments by Category",body:<ResponsiveContainer width="100%" height={220}><PieChart><Pie data={[{name:"Spam/Scam",value:1072},{name:"Rude",value:1223},{name:"Other",value:1516}]} dataKey="value" cx="50%" cy="50%" outerRadius={85} label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{[C.orange,C.red,C.gray400].map((c,i)=><Cell key={i} fill={c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>},
  };
  const c=content[metric]||{title:metric,body:<div style={{color:C.gray400,fontSize:13}}>Breakdown coming soon.</div>};
  return<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.4)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={onClose}><div style={{background:C.white,borderRadius:16,padding:28,width:560,maxWidth:"90vw",boxShadow:"0 20px 60px rgba(0,0,0,0.2)"}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:20}}><h2 style={{fontFamily:F.d,fontSize:18,fontWeight:800,color:C.dark}}>{c.title}</h2><button onClick={onClose} style={{background:C.gray100,border:"none",borderRadius:8,width:32,height:32,cursor:"pointer",fontSize:16,color:C.gray600}}>✕</button></div>{c.body}</div></div>;
}

// PAGES
function OverviewPage(){
  const[flags,setFlags]=useState([{id:1,platform:"FB",comment:"This service is terrible, I want a refund",intent:"Complaint",confidence:61,time:"2m ago"},{id:2,platform:"IG",comment:"Order SIM now earn 5000 PKR daily from home",intent:"Spam",confidence:74,time:"5m ago"},{id:3,platform:"TT",comment:"Network issues in my area since 3 days",intent:"Crisis",confidence:58,time:"12m ago"},{id:4,platform:"FB",comment:"Interested in 30GB plan, where can I buy?",intent:"Purchase",confidence:69,time:"18m ago"}]);
  const[drill,setDrill]=useState(null);
  const dismiss=id=>setFlags(f=>f.filter(x=>x.id!==id));
  return<div style={{display:"flex",flexDirection:"column",gap:20}}>
    <DrillDown metric={drill} onClose={()=>setDrill(null)}/>
    <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between"}}>
      <div><h1 style={{fontFamily:F.d,fontSize:20,fontWeight:800,color:C.dark}}>Morning Briefing</h1><p style={{fontSize:12,color:C.gray400,marginTop:2}}>Thursday, March 5 — Here's what happened since you were last here</p></div>
      <div style={{display:"flex",gap:7}}><SPill platform="Facebook" status="green"/><SPill platform="Instagram" status="green"/><SPill platform="TikTok" status="amber"/></div>
    </div>
    <div style={{display:"flex",gap:10}}>
      <KTile label="Comments Today" value="7,407" delta={18} deltaLabel="vs yesterday" onClick={()=>setDrill("Comments Today")} active={drill==="Comments Today"}/>
      <KTile label="Auto-Processed" value="87%" delta={-2} deltaLabel="vs yesterday" onClick={()=>setDrill("Auto-Processed")} active={drill==="Auto-Processed"}/>
      <KTile label="Comments Hidden" value="3,811" delta={12} deltaLabel="vs yesterday" onClick={()=>setDrill("Comments Hidden")} active={drill==="Comments Hidden"}/>
      <KTile label="Response Rate" value="64%" delta={-5} deltaLabel="vs yesterday" onClick={()=>setDrill("Response Rate")} active={drill==="Response Rate"}/>
      <KTile label="Backlog" value="142" deltaLabel="oldest: 3h 20m"/>
      <KTile label="Hours Saved" value="269h" deltaLabel="≈ PKR 134,500" dark/>
    </div>
    <Card><SLabel color={C.indigo}>Intent Snapshot — Today</SLabel><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{intentData.map(item=><div key={item.label} style={{flex:"1 1 110px",background:C.bg,borderRadius:10,padding:"12px 13px",border:`1px solid ${C.gray100}`}}><div style={{display:"flex",alignItems:"center",gap:5,marginBottom:5}}><div style={{width:7,height:7,borderRadius:"50%",background:item.color}}/><span style={{fontSize:10,color:C.gray400,fontWeight:500}}>{item.label}</span></div><div style={{fontFamily:F.d,fontSize:20,fontWeight:800,color:C.dark}}>{item.count.toLocaleString()}</div><div style={{fontSize:10,color:C.gray400,marginTop:2}}>{item.pct}%</div></div>)}</div></Card>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
      <Card><SLabel color={C.indigo}>Comment Inflow by Hour</SLabel><ResponsiveContainer width="100%" height={170}><AreaChart data={hourlyData} margin={{top:0,right:0,left:-20,bottom:0}}><defs><linearGradient id="cg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.indigo} stopOpacity={0.15}/><stop offset="95%" stopColor={C.indigo} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="h" tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{fontSize:12,borderRadius:8}}/><Area type="monotone" dataKey="comments" stroke={C.indigo} strokeWidth={2} fill="url(#cg)" name="Comments"/><Area type="monotone" dataKey="spam" stroke={C.red} strokeWidth={1.5} fill="none" name="Spam" strokeDasharray="4 2"/></AreaChart></ResponsiveContainer></Card>
      <Card>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}><SLabel color={C.amber}>Flagged for Review</SLabel><span style={{background:C.amberLight,color:C.amber,fontSize:11,fontWeight:700,padding:"2px 8px",borderRadius:20}}>{flags.length} pending</span></div>
        <div style={{display:"flex",flexDirection:"column",gap:7}}>
          {flags.length===0&&<div style={{textAlign:"center",color:C.gray400,fontSize:12,padding:"20px 0"}}>All clear ✓</div>}
          {flags.map(item=><div key={item.id} style={{display:"flex",alignItems:"center",gap:8,padding:"9px 11px",background:C.bg,borderRadius:8,border:`1px solid ${C.gray100}`}}><PBadge p={item.platform}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,color:C.gray700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{item.comment}</div><div style={{fontSize:10,color:C.gray400,marginTop:2}}>{item.intent} · {item.confidence}% · {item.time}</div></div><div style={{display:"flex",gap:5}}><button onClick={()=>dismiss(item.id)} style={{background:C.greenLight,color:C.green,border:"none",borderRadius:6,padding:"3px 9px",fontSize:11,fontWeight:700,cursor:"pointer"}}>✓</button><button onClick={()=>dismiss(item.id)} style={{background:C.redLight,color:C.red,border:"none",borderRadius:6,padding:"3px 9px",fontSize:11,fontWeight:700,cursor:"pointer"}}>✗</button></div></div>)}
        </div>
      </Card>
    </div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
      <Card><SLabel color={C.red}>Top Posts by Spam Ratio</SLabel>{[...topPosts].sort((a,b)=>b.spam-a.spam).map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"9px 0",borderBottom:i<4?`1px solid ${C.gray100}`:"none"}}><span style={{fontFamily:F.d,fontSize:13,fontWeight:800,color:C.gray200,width:18}}>{i+1}</span><PBadge p={p.platform}/><span style={{flex:1,fontSize:12,color:C.gray700,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p.title}</span><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:55,height:5,background:C.gray100,borderRadius:3,overflow:"hidden"}}><div style={{width:`${p.spam}%`,height:"100%",background:p.spam>25?C.red:p.spam>15?C.orange:C.amber,borderRadius:3}}/></div><span style={{fontSize:12,fontWeight:700,color:p.spam>25?C.red:p.spam>15?C.orange:C.amber}}>{p.spam}%</span></div></div>)}</Card>
      <Card><SLabel color={C.purple}>Trigger Activation Today</SLabel>{[...triggerData].sort((a,b)=>b.fires-a.fires).map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"9px 0",borderBottom:i<triggerData.length-1?`1px solid ${C.gray100}`:"none"}}><span style={{fontFamily:F.d,fontSize:13,fontWeight:800,color:C.gray200,width:18}}>{i+1}</span><span style={{flex:1,fontSize:12,color:C.gray700}}>{t.name}</span><span style={{fontSize:10,color:C.gray400,background:C.bg,padding:"2px 7px",borderRadius:4}}>{t.action}</span><span style={{fontFamily:F.d,fontSize:13,fontWeight:700,color:C.dark,width:38,textAlign:"right"}}>{t.fires.toLocaleString()}</span></div>)}</Card>
    </div>
    <Card><SLabel color={C.green}>Sentiment Trend — Last 30 Days</SLabel><ResponsiveContainer width="100%" height={160}><AreaChart data={sentimentData} margin={{top:0,right:0,left:-20,bottom:0}}><defs><linearGradient id="pg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.green} stopOpacity={0.3}/><stop offset="95%" stopColor={C.green} stopOpacity={0}/></linearGradient><linearGradient id="ng" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.red} stopOpacity={0.2}/><stop offset="95%" stopColor={C.red} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="day" tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{fontSize:12,borderRadius:8}}/><Area type="monotone" dataKey="positive" stroke={C.green} strokeWidth={2} fill="url(#pg)" name="Positive"/><Area type="monotone" dataKey="neutral" stroke={C.gray400} strokeWidth={1.5} fill="none" name="Neutral"/><Area type="monotone" dataKey="negative" stroke={C.red} strokeWidth={1.5} fill="url(#ng)" name="Negative"/></AreaChart></ResponsiveContainer></Card>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
      <Card><SLabel color={C.orange}>Recurring Complaint Themes</SLabel>{complaintThemes.map((c,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 0",borderBottom:i<4?`1px solid ${C.bg}`:"none"}}><span style={{fontSize:12,color:C.gray700,flex:1}}>{c.theme}</span><span style={{fontFamily:F.d,fontSize:13,fontWeight:700,color:C.dark,width:45,textAlign:"right"}}>{c.count}</span><span style={{fontSize:12,fontWeight:600,width:55,textAlign:"right",color:c.delta>0?C.red:C.green}}>{c.delta>0?"▲":"▼"} {Math.abs(c.delta)}</span></div>)}</Card>
      <Card><SLabel color={C.blue}>Platform Comparison</SLabel>{platformData.map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"10px 0",borderBottom:i<2?`1px solid ${C.bg}`:"none"}}><span style={{fontSize:12,fontWeight:600,color:C.gray700,flex:1}}>{p.platform}</span><span style={{fontSize:12,color:C.gray700}}>{p.comments.toLocaleString()}</span><span style={{fontSize:12,fontWeight:700,color:p.sentiment>40?C.green:p.sentiment>30?C.amber:C.red,width:45,textAlign:"right"}}>{p.sentiment}%</span><span style={{fontSize:12,fontWeight:700,color:p.spam>15?C.red:C.amber,width:45,textAlign:"right"}}>{p.spam}%</span></div>)}</Card>
    </div>
    <div style={{background:"linear-gradient(135deg,#0F172A,#1E3A5F)",borderRadius:14,padding:"24px 28px",display:"flex",alignItems:"center",justifyContent:"space-between"}}>
      <div><div style={{fontFamily:F.b,fontSize:11,color:C.gray400,letterSpacing:"0.08em",textTransform:"uppercase",marginBottom:6}}>This Month — Stanify Saved You</div><div style={{display:"flex",alignItems:"baseline",gap:12}}><span style={{fontFamily:F.d,fontSize:44,fontWeight:800,color:C.white}}>269</span><span style={{fontFamily:F.d,fontSize:20,fontWeight:600,color:C.gray400}}>hours</span><span style={{fontFamily:F.b,fontSize:13,color:C.green,fontWeight:600}}>≈ PKR 134,500 in team time</span></div></div>
      <button style={{background:C.white,color:C.dark,border:"none",borderRadius:10,padding:"12px 24px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:F.b}}>Download Monthly Report →</button>
    </div>
  </div>;
}

function InboxPage(){
  const[filter,setFilter]=useState("all");
  const[search,setSearch]=useState("");
  const intents=["all","Crisis","Complaint","Question","Purchase","Compliment"];
  const filtered=inboxItems.filter(i=>(filter==="all"||i.intent===filter)&&(search===""||i.comment.toLowerCase().includes(search.toLowerCase())||i.user.toLowerCase().includes(search.toLowerCase())));
  return<div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div><h1 style={{fontFamily:F.d,fontSize:20,fontWeight:800,color:C.dark}}>Inbox Analytics</h1><p style={{fontSize:12,color:C.gray400,marginTop:2}}>Backlog, priority queue and response tracking</p></div>
    <div style={{display:"flex",gap:10}}>
      {[["Facebook Backlog","68","oldest: 4h 12m"],["Instagram Backlog","41","oldest: 2h 55m"],["TikTok Backlog","33","oldest: 1h 38m"],["Total Backlog","142","oldest: 4h 12m"],["Avg Handle Time","4.2m","▼ 12% vs last week"],["Escalation Rate","2.5%","▼ 0.4% vs last week"]].map(([l,v,d])=><Card key={l} style={{flex:1}}><div style={{fontSize:10,color:C.gray400,fontWeight:600,marginBottom:6}}>{l}</div><div style={{fontFamily:F.d,fontSize:24,fontWeight:800,color:C.dark}}>{v}</div><div style={{fontSize:11,color:C.amber,marginTop:4}}>{d}</div></Card>)}
    </div>
    <Card><SLabel color={C.indigo}>Comment Inflow by Hour</SLabel><ResponsiveContainer width="100%" height={150}><AreaChart data={hourlyData} margin={{top:0,right:0,left:-20,bottom:0}}><defs><linearGradient id="icg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.indigo} stopOpacity={0.15}/><stop offset="95%" stopColor={C.indigo} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="h" tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="comments" stroke={C.indigo} strokeWidth={2} fill="url(#icg)" name="Comments"/><Area type="monotone" dataKey="spam" stroke={C.red} strokeWidth={1.5} fill="none" name="Spam" strokeDasharray="4 2"/></AreaChart></ResponsiveContainer></Card>
    <Card>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}><SLabel color={C.indigo}>Priority Queue</SLabel><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search comments or users..." style={{border:`1px solid ${C.gray200}`,borderRadius:8,padding:"6px 12px",fontSize:12,color:C.gray700,width:220,fontFamily:F.b,outline:"none"}}/></div>
      <div style={{display:"flex",gap:6,marginBottom:14,flexWrap:"wrap"}}>{intents.map(i=><button key={i} onClick={()=>setFilter(i)} style={{background:filter===i?C.dark:C.bg,color:filter===i?C.white:C.gray600,border:`1px solid ${filter===i?C.dark:C.gray200}`,borderRadius:20,padding:"4px 12px",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:F.b}}>{i==="all"?"All Intents":i}</button>)}</div>
      <div style={{display:"grid",gridTemplateColumns:"70px 1fr 90px 80px 80px 65px",gap:8,padding:"0 0 8px",borderBottom:`1px solid ${C.gray100}`}}>{["Platform","Comment","Intent","Sentiment","Status","Time"].map(h=><span key={h} style={{fontSize:10,fontWeight:600,color:C.gray400,textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</span>)}</div>
      {filtered.map((item,i)=><div key={item.id} style={{display:"grid",gridTemplateColumns:"70px 1fr 90px 80px 80px 65px",gap:8,padding:"11px 0",borderBottom:i<filtered.length-1?`1px solid ${C.bg}`:"none",alignItems:"center"}}><PBadge p={item.platform}/><div style={{minWidth:0}}><div style={{fontSize:12,color:C.gray700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{item.comment}</div><div style={{fontSize:10,color:C.gray400,marginTop:2}}>{item.user}</div></div><IBadge intent={item.intent}/><span style={{fontSize:11,fontWeight:600,color:item.sentiment==="Positive"?C.green:item.sentiment==="Negative"?C.red:C.gray400}}>{item.sentiment}</span><SBadge status={item.status}/><span style={{fontSize:11,color:C.gray400}}>{item.time}</span></div>)}
      {filtered.length===0&&<div style={{textAlign:"center",color:C.gray400,fontSize:12,padding:"20px 0"}}>No comments match this filter</div>}
    </Card>
    <Card><SLabel color={C.indigo}>Response Rate by Intent</SLabel><ResponsiveContainer width="100%" height={160}><BarChart data={responseRateData} margin={{top:0,right:0,left:-20,bottom:0}}><XAxis dataKey="intent" tick={{fontSize:11,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false} unit="%"/><Tooltip/><Bar dataKey="auto" name="Auto" fill={C.indigo} radius={[4,4,0,0]}/><Bar dataKey="manual" name="Manual" fill="#C7D2FE" radius={[4,4,0,0]}/><Legend/></BarChart></ResponsiveContainer></Card>
  </div>;
}

function AutomationPage(){
  const[sel,setSel]=useState(null);
  return<div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div><h1 style={{fontFamily:F.d,fontSize:20,fontWeight:800,color:C.dark}}>Automation Health</h1><p style={{fontSize:12,color:C.gray400,marginTop:2}}>Trigger performance, override rates and flagged actions</p></div>
    <div style={{display:"flex",gap:10}}>{[["Auto-hide Rate","51.5%",null,"of total comments"],["Auto-reply Rate","16.7%",null,"of eligible"],["Override Rate","1.8%",-0.4,"vs last week"],["Escalation Rate","2.5%",-0.4,"vs last week"],["Safety Filter","312",null,"actions this month"]].map(([l,v,d,dl])=><KTile key={l} label={l} value={v} delta={d} deltaLabel={dl}/>)}</div>
    <Card>
      <SLabel color={C.purple}>Trigger Leaderboard — click a row to expand</SLabel>
      <div style={{display:"grid",gridTemplateColumns:"1fr 80px 100px 90px 90px 90px",gap:8,padding:"0 0 8px",borderBottom:`1px solid ${C.gray100}`}}>{["Trigger","Fires","Action","Overrides","Precision",""].map(h=><span key={h} style={{fontSize:10,fontWeight:600,color:C.gray400,textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</span>)}</div>
      {[...triggerData].sort((a,b)=>b.fires-a.fires).map((t,i)=><div key={i}><div onClick={()=>setSel(sel===i?null:i)} style={{display:"grid",gridTemplateColumns:"1fr 80px 100px 90px 90px 90px",gap:8,padding:"11px 0",borderBottom:sel!==i?`1px solid ${C.bg}`:"none",alignItems:"center",cursor:"pointer",background:sel===i?"#F8FAFC":"transparent",borderRadius:sel===i?"8px 8px 0 0":8}}><span style={{fontSize:12,fontWeight:600,color:C.gray700}}>{t.name}</span><span style={{fontFamily:F.d,fontSize:14,fontWeight:800,color:C.dark}}>{t.fires.toLocaleString()}</span><span style={{fontSize:11,background:C.bg,color:C.gray600,padding:"2px 8px",borderRadius:4,display:"inline-block"}}>{t.action}</span><span style={{fontSize:12,color:t.overrides>10?C.red:C.amber,fontWeight:600}}>{t.overrides}</span><span style={{fontSize:12,fontWeight:700,color:t.precision>97?C.green:t.precision>94?C.amber:C.red}}>{t.precision}%</span><span style={{fontSize:11,color:sel===i?C.indigo:C.gray400}}>{sel===i?"▲ Hide":"▼ Details"}</span></div>
        {sel===i&&<div style={{background:"#F8FAFC",borderRadius:"0 0 8px 8px",padding:"16px",marginBottom:4,border:`1px solid ${C.gray100}`,borderTop:"none"}}>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
            <div><div style={{fontSize:12,color:C.gray400,marginBottom:10}}>Fires — last 7 days</div><ResponsiveContainer width="100%" height={120}><BarChart data={[{d:"Mon",v:142},{d:"Tue",v:198},{d:"Wed",v:167},{d:"Thu",v:210},{d:"Fri",v:189},{d:"Sat",v:88},{d:"Sun",v:78}]}><XAxis dataKey="d" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="v" fill={C.purple} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>
            <div style={{display:"flex",flexDirection:"column",gap:8}}>{[["Action",t.action,C.dark],["Precision",`${t.precision}%`,C.green],["Overrides",`${t.overrides} this month`,t.overrides>10?C.red:C.amber]].map(([l,v,c])=><div key={l} style={{background:C.white,borderRadius:8,padding:"10px 12px",border:`1px solid ${C.gray100}`}}><div style={{fontSize:11,color:C.gray400,marginBottom:3}}>{l}</div><div style={{fontSize:14,fontWeight:700,color:c}}>{v}</div></div>)}</div>
          </div>
        </div>}
      </div>)}
    </Card>
    <Card><SLabel color={C.amber}>Override Rate Trend</SLabel><ResponsiveContainer width="100%" height={140}><LineChart data={[{w:"W1",rate:3.2},{w:"W2",rate:2.8},{w:"W3",rate:2.1},{w:"W4",rate:1.8}]} margin={{top:0,right:0,left:-20,bottom:0}}><XAxis dataKey="w" tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false} unit="%"/><Tooltip/><Line type="monotone" dataKey="rate" stroke={C.amber} strokeWidth={2.5} dot={{fill:C.amber,r:4}} name="Override Rate %"/></LineChart></ResponsiveContainer><div style={{fontSize:12,color:C.green,marginTop:6}}>▼ Override rate declining — automation improving over time</div></Card>
  </div>;
}

function SpamCrisisPage(){
  const maxV=Math.max(...heatmapData.flatMap(d=>d.hours.map(h=>h.v)));
  return<div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div><h1 style={{fontFamily:F.d,fontSize:20,fontWeight:800,color:C.dark}}>Spam & Crisis Intelligence</h1><p style={{fontSize:12,color:C.gray400,marginTop:2}}>Attack patterns, spam ratios, and crisis detection</p></div>
    <div style={{display:"flex",gap:10}}>{[["Spam Caught","1,072",-57,"vs last month"],["Avg Spam Ratio","14.5%",3,"vs last month"],["Crisis Alerts","3",null,"this month"],["Spam Contained","98.2%",null,"before public reaction"],["Ad Post Spam","28.4%",8,"vs organic 8.1%"]].map(([l,v,d,dl])=><KTile key={l} label={l} value={v} delta={d} deltaLabel={dl}/>)}</div>
    <div style={{background:"#FEF2F2",border:"1px solid #FECACA",borderRadius:12,padding:"14px 18px",display:"flex",alignItems:"center",gap:12}}><div style={{width:10,height:10,borderRadius:"50%",background:C.red,flexShrink:0}}/><div style={{flex:1}}><span style={{fontSize:13,fontWeight:700,color:C.red}}>Crisis Alert — </span><span style={{fontSize:13,color:"#991B1B"}}>Network complaint spike on TikTok (+340% in last 2h). Post: "Laal Network vs Onic"</span></div><button style={{background:C.red,color:C.white,border:"none",borderRadius:8,padding:"6px 14px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:F.b,flexShrink:0}}>View Post →</button></div>
    <Card>
      <SLabel color={C.red}>Comment Inflow Heatmap — Hour × Day</SLabel>
      <div style={{display:"flex",gap:4,alignItems:"flex-start"}}>
        <div style={{display:"flex",flexDirection:"column",gap:4,paddingTop:22}}>{heatmapData.map(d=><div key={d.day} style={{height:26,display:"flex",alignItems:"center",fontSize:11,color:C.gray400,width:32}}>{d.day}</div>)}</div>
        <div style={{flex:1}}><div style={{display:"flex",gap:4,marginBottom:4}}>{heatmapData[0].hours.map(h=><div key={h.h} style={{flex:1,fontSize:9,color:C.gray400,textAlign:"center"}}>{h.h}</div>)}</div>{heatmapData.map(d=><div key={d.day} style={{display:"flex",gap:4,marginBottom:4}}>{d.hours.map(h=><div key={h.h} title={`${d.day} ${h.h}: ${h.v}`} style={{flex:1,height:26,borderRadius:5,background:`rgba(239,68,68,${0.05+(h.v/maxV)*0.85})`,cursor:"default"}}/>)}</div>)}</div>
      </div>
      <div style={{display:"flex",alignItems:"center",gap:6,marginTop:10}}><span style={{fontSize:11,color:C.gray400}}>Low</span>{[0.1,0.3,0.5,0.7,0.9].map(v=><div key={v} style={{width:20,height:12,borderRadius:3,background:`rgba(239,68,68,${v})`}}/>)}<span style={{fontSize:11,color:C.gray400}}>High</span></div>
    </Card>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
      <Card><SLabel color={C.red}>Posts Ranked by Spam Ratio</SLabel>{[...topPosts].sort((a,b)=>b.spam-a.spam).map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:i<4?`1px solid ${C.bg}`:"none"}}><span style={{fontFamily:F.d,fontSize:13,fontWeight:800,color:C.gray200,width:18}}>{i+1}</span><PBadge p={p.platform}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,color:C.gray700,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p.title}</div><div style={{fontSize:10,color:C.gray400,marginTop:1}}>{p.comments.toLocaleString()} comments</div></div><div style={{textAlign:"right",flexShrink:0}}><div style={{fontFamily:F.d,fontSize:14,fontWeight:800,color:p.spam>25?C.red:p.spam>15?C.orange:C.amber}}>{p.spam}%</div><div style={{fontSize:9,color:C.gray400}}>spam</div></div></div>)}</Card>
      <Card>
        <SLabel color={C.blue}>Mentions Intelligence</SLabel>
        <div style={{background:"#FEF9C3",border:"1px solid #FDE68A",borderRadius:8,padding:"10px 12px",marginBottom:12}}><div style={{fontSize:11,fontWeight:600,color:"#92400E"}}>Mentions: Like and Reply only — Hiding not available</div></div>
        {[{platform:"FB",source:"Tech Review PK",comment:"Is ONIC better than Jazz for data?",intent:"Question",time:"1h ago"},{platform:"TT",source:"Mobile Reviews",comment:"ONIC 30GB plan is actually great value",intent:"Compliment",time:"3h ago"},{platform:"IG",source:"Pakistan Tech",comment:"Anyone else having issues with ONIC network?",intent:"Complaint",time:"5h ago"}].map((m,i)=><div key={i} style={{padding:"10px 0",borderBottom:i<2?`1px solid ${C.bg}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><PBadge p={m.platform}/><span style={{fontSize:11,fontWeight:600,color:C.gray600}}>{m.source}</span><span style={{fontSize:10,color:C.gray400,marginLeft:"auto"}}>{m.time}</span></div><div style={{fontSize:12,color:C.gray700}}>{m.comment}</div><div style={{display:"flex",gap:6,marginTop:6}}><IBadge intent={m.intent}/><button style={{background:C.greenLight,color:C.green,border:"none",borderRadius:5,padding:"2px 9px",fontSize:10,fontWeight:700,cursor:"pointer"}}>♥ Like</button><button style={{background:C.indigoLight,color:C.indigo,border:"none",borderRadius:5,padding:"2px 9px",fontSize:10,fontWeight:700,cursor:"pointer"}}>↩ Reply</button></div></div>)}
      </Card>
    </div>
  </div>;
}

function EngagementPage(){
  return<div style={{display:"flex",flexDirection:"column",gap:18}}>
    <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between"}}>
      <div><h1 style={{fontFamily:F.d,fontSize:20,fontWeight:800,color:C.dark}}>Engagement & Intent</h1><p style={{fontSize:12,color:C.gray400,marginTop:2}}>Weekly brand performance and audience intelligence</p></div>
      <button style={{background:C.dark,color:C.white,border:"none",borderRadius:10,padding:"10px 20px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:F.b}}>Download Monthly Report →</button>
    </div>
    <div style={{display:"flex",gap:10}}>{[["Response Rate","64%",-5,"vs last month"],["Reengagement Rate","43%",8,"vs last month"],["Unique Commenters","3,979",12,"vs last month"],["Purchase Intent","424",null,"62% got a response"],["Hours Saved","269h",null,"≈ PKR 134,500",true]].map(([l,v,d,dl,dk])=><KTile key={l} label={l} value={v} delta={d} deltaLabel={dl} dark={dk}/>)}</div>
    <Card><SLabel color={C.green}>Engagement Trends — This Month</SLabel><ResponsiveContainer width="100%" height={170}><LineChart data={engagementTrend} margin={{top:0,right:0,left:-20,bottom:0}}><XAxis dataKey="week" tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><Tooltip/><Line type="monotone" dataKey="responseRate" stroke={C.indigo} strokeWidth={2.5} dot={{fill:C.indigo,r:4}} name="Response Rate %"/><Line type="monotone" dataKey="reengagement" stroke={C.green} strokeWidth={2.5} dot={{fill:C.green,r:4}} name="Reengagement %"/><Legend/></LineChart></ResponsiveContainer></Card>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
      <Card><SLabel color={C.green}>Sentiment Trend — 30 Days</SLabel><ResponsiveContainer width="100%" height={170}><AreaChart data={sentimentData} margin={{top:0,right:0,left:-20,bottom:0}}><defs><linearGradient id="epg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={C.green} stopOpacity={0.3}/><stop offset="95%" stopColor={C.green} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="day" tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:C.gray400}} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="positive" stroke={C.green} strokeWidth={2} fill="url(#epg)" name="Positive"/><Area type="monotone" dataKey="neutral" stroke={C.gray400} strokeWidth={1.5} fill="none" name="Neutral"/><Area type="monotone" dataKey="negative" stroke={C.red} strokeWidth={1.5} fill="none" name="Negative"/><Legend/></AreaChart></ResponsiveContainer></Card>
      <Card><SLabel color={C.indigo}>Intent Mix — This Month</SLabel><ResponsiveContainer width="100%" height={170}><PieChart><Pie data={intentData.map(d=>({name:d.label,value:d.count}))} dataKey="value" cx="50%" cy="50%" outerRadius={72} label={({percent})=>`${(percent*100).toFixed(0)}%`} labelLine={false}>{intentData.map((d,i)=><Cell key={i} fill={d.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Card>
    </div>
    <Card><SLabel color={C.blue}>Platform Comparison</SLabel><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8,padding:"0 0 10px",borderBottom:`1px solid ${C.gray100}`,marginBottom:4}}>{["Platform","Comments","Sentiment","Response Rate","Spam Rate"].map(h=><span key={h} style={{fontSize:10,fontWeight:600,color:C.gray400,textTransform:"uppercase",letterSpacing:"0.05em"}}>{h}</span>)}</div>{platformData.map((p,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:8,padding:"12px 0",borderBottom:i<2?`1px solid ${C.bg}`:"none",alignItems:"center"}}><span style={{fontSize:13,fontWeight:700,color:C.dark}}>{p.platform}</span><span style={{fontFamily:F.d,fontSize:15,fontWeight:800,color:C.dark}}>{p.comments.toLocaleString()}</span><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:45,height:5,background:C.gray100,borderRadius:3,overflow:"hidden"}}><div style={{width:`${p.sentiment}%`,height:"100%",background:p.sentiment>40?C.green:p.sentiment>30?C.amber:C.red,borderRadius:3}}/></div><span style={{fontSize:12,fontWeight:700,color:p.sentiment>40?C.green:p.sentiment>30?C.amber:C.red}}>{p.sentiment}%</span></div><span style={{fontSize:12,fontWeight:700,color:C.indigo}}>{p.responseRate}%</span><span style={{fontSize:12,fontWeight:700,color:p.spam>15?C.red:C.amber}}>{p.spam}%</span></div>)}</Card>
    <Card><SLabel color={C.green}>Top Posts by Positive Sentiment</SLabel>{[...topPosts].sort((a,b)=>b.sentiment-a.sentiment).map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"10px 0",borderBottom:i<4?`1px solid ${C.bg}`:"none"}}><span style={{fontFamily:F.d,fontSize:14,fontWeight:800,color:C.gray200,width:22}}>{i+1}</span><PBadge p={p.platform}/><span style={{flex:1,fontSize:12,color:C.gray700}}>{p.title}</span><span style={{fontSize:11,color:C.gray400}}>{p.comments.toLocaleString()} comments</span><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:80,height:5,background:C.gray100,borderRadius:3,overflow:"hidden"}}><div style={{width:`${p.sentiment}%`,height:"100%",background:C.green,borderRadius:3}}/></div><span style={{fontSize:12,fontWeight:700,color:C.green,width:34,textAlign:"right"}}>{p.sentiment}%</span></div></div>)}</Card>
    <Card><SLabel color={C.orange}>Recurring Complaint Themes</SLabel><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{complaintThemes.map((c,i)=><div key={i} style={{background:C.bg,borderRadius:10,padding:"14px 16px",border:`1px solid ${C.gray100}`}}><div style={{fontSize:11,color:C.gray400,fontWeight:500,marginBottom:6}}>{c.theme}</div><div style={{fontFamily:F.d,fontSize:22,fontWeight:800,color:C.dark}}>{c.count}</div><div style={{fontSize:11,fontWeight:700,color:c.delta>0?C.red:C.green,marginTop:4}}>{c.delta>0?"▲":"▼"} {Math.abs(c.delta)} vs last month</div></div>)}</div></Card>
  </div>;
}

const PAGES=[{id:"overview",label:"Overview"},{id:"inbox",label:"Inbox"},{id:"automation",label:"Automation"},{id:"spam",label:"Spam & Crisis"},{id:"engagement",label:"Engagement"}];

export default function App(){
  const[page,setPage]=useState("overview");
  const render = () => {
    switch(page) {
      case "overview": return <OverviewPage />;
      case "inbox": return <InboxPage />;
      case "automation": return <AutomationPage />;
      case "spam": return <SpamCrisisPage />;
      case "engagement": return <EngagementPage />;
      default: return <OverviewPage />;
    }
  };
  return<>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500;600&display=swap');*{box-sizing:border-box;margin:0;padding:0;}body{background:#F8FAFC;}::-webkit-scrollbar{width:5px;}::-webkit-scrollbar-thumb{background:#CBD5E1;border-radius:3px;}button{transition:opacity 0.1s;}button:hover{opacity:0.85;}`}</style>
    <div style={{minHeight:"100vh",background:"#F8FAFC",fontFamily:F.b}}>
      <div style={{background:C.white,borderBottom:`1px solid ${C.gray100}`,padding:"0 32px",display:"flex",alignItems:"center",justifyContent:"space-between",height:54,position:"sticky",top:0,zIndex:100}}>
        <div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:26,height:26,background:C.dark,borderRadius:7,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{color:C.white,fontSize:13,fontWeight:800,fontFamily:F.d}}>S</span></div><span style={{fontFamily:F.d,fontWeight:700,fontSize:15,color:C.dark}}>Stanify</span><span style={{background:C.gray100,color:C.gray600,fontSize:10,fontWeight:600,padding:"2px 8px",borderRadius:4}}>Onic PK</span></div>
        <div style={{display:"flex",gap:4}}>{PAGES.map(p=><button key={p.id} onClick={()=>setPage(p.id)} style={{background:page===p.id?C.dark:"transparent",color:page===p.id?C.white:C.gray600,border:"none",borderRadius:6,padding:"6px 14px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:F.b}}>{p.label}</button>)}</div>
        <div style={{display:"flex",alignItems:"center",gap:10}}><select style={{border:`1px solid ${C.gray200}`,borderRadius:6,padding:"5px 10px",fontSize:11,color:C.gray700,background:C.white,fontFamily:F.b}}><option>Last 30 days</option><option>Last 7 days</option><option>Today</option></select><div style={{width:30,height:30,borderRadius:"50%",background:C.indigo,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:12,fontWeight:700}}>A</div></div>
      </div>
      <div style={{maxWidth:1400,margin:"0 auto",padding:"24px 32px"}}>{render()}</div>
    </div>
  </>;
}
